# Generated by Django 4.1 on 2022-08-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_rekening", models.CharField(max_length=255, null=True)),
                ("nama_rekening", models.CharField(max_length=255, null=True)),
                ("nama_bank", models.CharField(max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="kode",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_invoice", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("List Of Claim", "List Of Claim"),
                            ("Invoice", "Invoice"),
                            ("MCM", "MCM"),
                            ("Payment", "Payment"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tipe",
                    models.CharField(
                        blank=True,
                        choices=[("OPR", "OPR"), ("INVS", "INVS"), ("PDN", "PDN")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("no_pr", models.CharField(blank=True, max_length=255, null=True)),
                ("nama_vendor", models.CharField(max_length=255, null=True)),
                ("deskripsi", models.CharField(max_length=255, null=True)),
                ("nominal", models.FloatField(max_length=255, null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoice.department",
                    ),
                ),
            ],
        ),
    ]
