# Generated by Django 4.1 on 2022-08-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_bank_department_kode_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="deskripsi",
            field=models.TextField(blank=True, null=True),
        ),
    ]
