# Generated by Django 4.1 on 2022-08-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_alter_invoice_deskripsi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="department",
        ),
        migrations.AddField(
            model_name="bank",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoice.department",
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoice.invoice",
            ),
        ),
    ]
