# Generated by Django 4.1 on 2022-08-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_remove_invoice_department_bank_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="department",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="nominal",
        ),
        migrations.AddField(
            model_name="bank",
            name="nominal",
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoice.department",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="email",
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
