# Generated by Django 4.1 on 2022-08-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0007_invoice_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="department",
        ),
    ]
