# Generated by Django 4.1 on 2022-08-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0008_remove_invoice_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("List Of Claim", "List Of Claim"),
                    ("Invoice", "Invoice"),
                    ("MCM", "MCM"),
                    ("Payment", "Payment"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
