# Generated by Django 4.1 on 2022-08-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0009_alter_invoice_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="status",
        ),
    ]
