# Generated by Django 4.1 on 2022-08-29 01:01

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0011_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="attachment",
            field=models.FileField(default=1, upload_to=invoice.models.file_path),
            preserve_default=False,
        ),
    ]
