# Generated by Django 4.1 on 2022-09-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0013_invoice_nominal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="nominal",
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tipe",
            field=models.CharField(
                choices=[("OPR", "OPR"), ("INVS", "INVS"), ("PDN", "PDN")],
                max_length=255,
                null=True,
            ),
        ),
    ]
