# Generated by Django 4.1 on 2022-09-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0014_alter_invoice_nominal_alter_invoice_tipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="tipe",
            field=models.CharField(
                choices=[
                    ("Operation", "Operation"),
                    ("Investasi", "Investasi"),
                    ("Pendanaan", "Pendanaan"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
