# Generated by Django 4.1 on 2022-09-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0015_alter_invoice_tipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="jenis_potongan",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="nilai_potongan",
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
    ]
