# Generated by Django 4.1.1 on 2022-09-18 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0016_invoice_jenis_potongan_invoice_nilai_potongan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='jenis_potongan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_user', models.CharField(choices=[('User Department', 'User Department'), ('User Invocie', 'User Invocie'), ('User Cashier', 'User Cashier'), ('User Payment', 'User Payment')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
