# Generated by Django 4.1.1 on 2022-09-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_alter_invoice_jenis_potongan_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group_user',
            field=models.CharField(choices=[('User Department', 'User Department'), ('User Invoice', 'User Invoice'), ('User Cashier', 'User Cashier'), ('User Payment', 'User Payment')], max_length=255),
        ),
    ]
