# Generated by Django 4.1.1 on 2022-09-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_alter_account_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
