# Generated by Django 4.1.1 on 2022-09-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_invoice_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='nilai_potongan',
            new_name='nilai_pot_bank',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='jenis_potongan',
        ),
        migrations.AddField(
            model_name='invoice',
            name='nilai_pot_pajak',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
    ]
