# Generated by Django 4.1.1 on 2022-09-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_rename_nilai_potongan_invoice_nilai_pot_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bayar',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
    ]
