# Generated by Django 4.1.1 on 2022-09-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_invoice_bayar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='nilai_pot_bank',
            new_name='pot_bank',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='nilai_pot_pajak',
            new_name='pot_pajak',
        ),
    ]
