# Generated by Django 4.1.1 on 2022-09-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_invoice_jenis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='jenis',
            new_name='kompensasi',
        ),
    ]
