# Generated by Django 4.1.1 on 2022-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_rename_jenis_invoice_kompensasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='kompensasi',
            field=models.BooleanField(default=False, verbose_name='Kompensasi'),
        ),
    ]
