# Generated by Django 4.1.1 on 2022-09-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('List Of Claim', 'List Of Claim'), ('Invoice', 'Invoice'), ('MCM', 'MCM'), ('Payment', 'Payment'), ('Payment Cabang', 'Payment Cabang')], max_length=255, null=True),
        ),
    ]
