# Generated by Django 4.1.1 on 2022-09-25 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0028_invoice_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='jenis',
            field=models.CharField(blank=True, choices=[('Kompensasi', 'Kompensasi'), ('Payment Cabang', 'Payment Cabang')], max_length=255, null=True),
        ),
    ]
