# Generated by Django 4.1.1 on 2022-09-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0029_alter_bank_invoice_alter_invoice_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='no_payment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
