# Generated by Django 4.1.1 on 2022-09-26 05:56

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0030_invoice_no_payment_invoice_payment_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bukti_transfer',
            field=models.FileField(default=1, upload_to=invoice.models.file_path_buktitransfer),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(default=1, upload_to=invoice.models.file_path),
        ),
    ]
