# Generated by Django 4.1.1 on 2022-09-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0032_alter_invoice_jenis_alter_invoice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='bukti_transfer',
            new_name='buktitransfer',
        ),
    ]
