# Generated by Django 4.1.1 on 2022-09-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0033_rename_bukti_transfer_invoice_buktitransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mcm_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
