# Generated by Django 4.1.1 on 2022-09-27 05:30

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0034_invoice_mcm_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buktitransfer',
            field=models.FileField(blank=True, upload_to=invoice.models.file_path_buktitransfer),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='no_payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
