# Generated by Django 4.1.1 on 2022-09-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0036_alter_invoice_attachment_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='estimasi_bayar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
