# Generated by Django 4.1.1 on 2022-09-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0038_bank_potongan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pot_bank',
        ),
    ]
