# Generated by Django 4.1.1 on 2022-09-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0039_remove_invoice_pot_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='potongan',
            new_name='biaya_admin',
        ),
    ]
