# Generated by Django 4.1.1 on 2022-09-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0040_rename_potongan_bank_biaya_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='total_bayar',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
    ]
