# Generated by Django 4.1.1 on 2022-09-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0041_bank_total_bayar'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pot_bank',
            field=models.FloatField(default=0, max_length=255, null=True),
        ),
    ]
