# Generated by Django 4.1.1 on 2022-10-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0043_invoice_filecsv_alter_account_group_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group_user',
            field=models.CharField(choices=[('User Department', 'User Department'), ('User Invoice', 'User Invoice'), ('User Cashier', 'User Cashier'), ('User Payment', 'User Payment'), ('User Payroll', 'User Payroll'), ('User Accounting', 'User Accounting')], max_length=255),
        ),
    ]
