# Generated by Django 4.1.1 on 2022-10-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0044_alter_account_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='no_invoice',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
