# Generated by Django 4.1.1 on 2022-10-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0045_alter_invoice_no_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='site_vendor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
