# Generated by Django 4.1.1 on 2022-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0046_invoice_site_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payroll_create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
