# Generated by Django 4.1.1 on 2022-10-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0047_invoice_payroll_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='kompensasi_create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
