# Generated by Django 4.1.1 on 2022-10-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0048_invoice_kompensasi_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('List Of Claim', 'List Of Claim'), ('Invoice', 'Invoice'), ('MCM', 'MCM'), ('Payment', 'Payment'), ('Kompensasi', 'Kompensasi'), ('Payment Kompensasi', 'Payment Kompensasi'), ('Payment Cabang', 'Payment Cabang'), ('Payroll', 'Payroll')], max_length=255, null=True),
        ),
    ]
