# Generated by Django 4.1.1 on 2022-10-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0049_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bayar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahap', models.CharField(max_length=255, null=True)),
                ('nominal', models.FloatField(default=0, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='invoice.invoice')),
            ],
        ),
    ]
