# Generated by Django 4.1.1 on 2022-10-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0050_bayar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bayar',
            new_name='BayarThp',
        ),
    ]
