# Generated by Django 4.1.1 on 2022-10-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0051_rename_bayar_bayarthp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BayarThp',
            new_name='PaymentTerm',
        ),
    ]
